# ----
ARG GO_VERSION=1
FROM golang:${GO_VERSION}-bookworm as builder

WORKDIR /usr/src/app
COPY tlsproxy/go.mod tlsproxy/go.sum ./
RUN go mod download && go mod verify
COPY tlsproxy/. .
RUN go build -v -o tlsproxy main.go

# ----
FROM debian:bookworm

COPY --from=builder /usr/src/app/tlsproxy /usr/local/bin/

WORKDIR /etc
CMD ["tlsproxy"]
